join-messages: ["swords up!", "call in the cavalry!", "seal the blast doors!"]
#Naming convention, just add a comma and a new string in between quotes. IE change it from
#join-messages: ["swords up!", "call in the cavalry!", "seal the blast doors!"]
#and add a new value "batten the hatches!"
#join-messages: ["swords up!", "call in the cavalry!", "seal the blast doors!", "batten the hatches!"]
