name: JacobsMMO
version: 1.1
author: Chase Witzansky
main: xyz.chasew.jacobsmmo.JacobsMMO
api-version: 1.13

commands:
  edititem:
    description: Edit an item's properties (the one you're holding)
    usage: /edititem <property> <value> [change]
  backifnear:
    description: Push player back if they're close to the block. Radius is the radius of closeness and back is the direction to go back (-x, -y, -z, +x, +y, +z)
    usage: /backifnear <radius> <backdir> <blockblack> <force>