name: JacobsMMO
version: 1.1
author: Chase Witzansky
main: xyz.chasew.jacobsmmo.JacobsMMO
api-version: 1.13

commands:
  edititem:
    description: Edit an item's properties (the one you're holding)
    usage: /edititem <property> <value> [change]
    permission: minecraft.op
  backifnear:
    description: Push player back if they're close to the block. Radius is the radius of closeness and back is the direction to go back (-x, -y, -z, +x, +y, +z)
    usage: /backifnear <radius> <backdir> <blockblack> <force>
  givespecialweapon:
    description: Give one of the weapon items
    usage: /givespecialweapon <playername> <item>
    permission: minecraft.op
  specialeffect:
    description: Effect presets
    usage: /specialeffect <preset> <rootx> <rooty> <rootz>
    permission: minecraft.op
  rotateallentities:
    description: Command to rotate all entities with specified tag (Loop it)
    usage: /rotateallentities <tagname> <amountYaw> <amountPitch>
    permission: minecraft.op
  givespecial:
    description: Give special item
    usage: /givespecial <selector> <item> <amount>
    permission: minecraft.op